spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  hibernate:
    ddl-auto: validate
  datasource:
    url: jdbc:mysql://localhost:3306/mini_practice?useSSL=false&useUnicode=true&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root1234!!

security:
  user:
    password: 1

jwt:
  accessToken:
    plus-hour: 3
  refreshToken:
    plus-hour: 12
  secretKey: MiniProjectPracticeJWTSecretKey1234567890
